### PR TITLE
A few visual enhancements when sitting on stairs

### PR DESCRIPTION
**Pull request by WerDei**
Hello! I've made some modifications to make sitting on stairs look a bit better.
1. When sitting on stairs, player's legs will always be facing where the stairs are facing (right now it depends from where the player clicks on the stair block);
2. Additionally, sitting position will be shifted a 3/16th of a block to make sure player's body doesn't look like it's inside the stairs.

 Sitting on the slab or with a /sit command were not affected by these changes.

Before:

After:

### CODE REVIEW

**Comment by BradBot1** [comment]
Hey, thanks so much for the pull request! I will look at the code when I get home. If I was to pull I would like to add you to the credits, is there any page you want me to link to for that?

**Comment by WerDei** [comment]
Just adding "WerDei" somewhere would be fine by me c:

**Comment by BradBot1** [comment]
Just play tested it and everything seems to be in order, ill pull shortly. Thank you so much for the pull request <3

**Comment by WerDei** [comment]
Thank you for merging! If I make any more tweaks I'll make sure to share them too c;

**Pull request merged**
